In [1]:
import numpy as np

In [2]:
d1 = np.array([1, 2, 3, 4, 5])
print(d1)


[1 2 3 4 5]


In [3]:
d2 = np.array([[1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]])
print(d2)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
d3= np.array([
    [[1, 2, 3],
    [4, 5, 6]],
    [[7, 8, 9],
    [10, 11, 12]]])
print(d3)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [5]:
d4 = np.array([[[[1, 2],
    [3, 4]],
    [[5, 6],
    [7, 8]]],
    [[[9, 10],  
    [11, 12]],
    [[13, 14],
    [15, 16]]]])
print(d4)


[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]]


In [6]:
d5 = np.array([
    [
        [
            [
                [
                    [1, 2],
                    [3, 4]
                ],
                [
                    [5, 6],
                    [7, 8]
                ]
            ],
            [
                [
                    [9, 10],
                    [11, 12]
                ],
                [
                    [13, 14],
                    [15, 16]
                ]
            ]
        ],
        [
            [
                [
                    [17, 18],
                    [19, 20]
                ],
                [
                    [21, 22],
                    [23, 24]
                ]
            ],
            [
                [
                    [25, 26],
                    [27, 28]
                ],
                [
                    [29, 30],
                    [31, 32]
                ]
            ]
        ]
    ]
])
print(d5)


[[[[[[ 1  2]
     [ 3  4]]

    [[ 5  6]
     [ 7  8]]]


   [[[ 9 10]
     [11 12]]

    [[13 14]
     [15 16]]]]



  [[[[17 18]
     [19 20]]

    [[21 22]
     [23 24]]]


   [[[25 26]
     [27 28]]

    [[29 30]
     [31 32]]]]]]


In [7]:
da1 = np.array([1, 2, 3, 4, 5])
da2 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
da3 = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])
da4 = np.array([
    [
        [
            [1, 2],
            [3, 4]
        ],
        [
            [5, 6],
            [7, 8]
        ]
    ],
    [
        [
            [9, 10],
            [11, 12]
        ],
        [
            [13, 14],
            [15, 16]
        ]
    ]
])
da5 = np.array([
    [
        [
            [
                [
                    [1, 2],
                    [3, 4]
                ],
                [
                    [5, 6],
                    [7, 8]
                ]
            ],
            [
                [
                    [9, 10],
                    [11, 12]
                ],
                [
                    [13, 14],
                    [15, 16]
                ]
            ]
        ],
        [
            [
                [
                    [17, 18],
                    [19, 20]
                ],
                [
                    [21, 22],
                    [23, 24]
                ]
            ],
            [
                [
                    [25, 26],
                    [27, 28]
                ],
                [
                    [29, 30],
                    [31, 32]
                ]
            ]
        ]
    ]
])

#determinant_1d = np.linalg.det(da1)
determinant_2d = np.linalg.det(da2)
#determinant_3d = np.linalg.det(da3)
determinant_4d = np.linalg.det(da4)
determinant_5d = np.linalg.det(da5)

#print("Determinant of 1-D Matrix (Vector):")
#print(determinant_1d)

print("\nDeterminant of 2-D Matrix:")
print(determinant_2d)

#print("\nDeterminant of 3-D Matrix (Tensor):")
#print(determinant_3)

print("\nDeterminant of 4-D Matrix:")
print(determinant_4d)

print("\nDeterminant of 5-D Matrix:")
print(determinant_5d)



Determinant of 2-D Matrix:
0.0

Determinant of 4-D Matrix:
[[-2. -2.]
 [-2. -2.]]

Determinant of 5-D Matrix:
[[[[-2. -2.]
   [-2. -2.]]

  [[-2. -2.]
   [-2. -2.]]]]


In [8]:
matrix_1d = np.array([1, 2, 3, 4, 5])
matrix_2d = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
matrix_3d = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])
matrix_4d = np.array([
    [
        [
            [1, 2],
            [3, 4]
        ],
        [
            [5, 6],
            [7, 8]
        ]
    ],
    [
        [
            [9, 10],
            [11, 12]
        ],
        [
            [13, 14],
            [15, 16]
        ]
    ]
])
matrix_5d = np.array([
    [
        [
            [
                [
                    [1, 2],
                    [3, 4]
                ],
                [
                    [5, 6],
                    [7, 8]
                ]
            ],
            [
                [
                    [9, 10],
                    [11, 12]
                ],
                [
                    [13, 14],
                    [15, 16]
                ]
            ]
        ],
        [
            [
                [
                    [17, 18],
                    [19, 20]
                ],
                [
                    [21, 22],
                    [23, 24]
                ]
            ],
            [
                [
                    [25, 26],
                    [27, 28]
                ],
                [
                    [29, 30],
                    [31, 32]
                ]
            ]
        ]
    ]
])
try:
    inverse_2d = np.linalg.inv(matrix_2d)
    print("Inverse of 2-D Matrix:")
    print(inverse_2d)
except np.linalg.LinAlgError:
    print("The 2-D matrix is not invertible.")

try:
    inverse_3d = np.linalg.inv(matrix_3d)
    print("\nInverse of 3-D Matrix (Tensor):")
    print(inverse_3d)
except np.linalg.LinAlgError:
    print("The 3-D matrix is not invertible.")

try:
    inverse_4d = np.linalg.inv(matrix_4d)
    print("\nInverse of 4-D Matrix:")
    print(inverse_4d)
except np.linalg.LinAlgError:
    print("The 4-D matrix is not invertible.")

try:
    inverse_5d = np.linalg.inv(matrix_5d)
    print("\nInverse of 5-D Matrix:")
    print(inverse_5d)
except np.linalg.LinAlgError:
    print("The 5-D matrix is not invertible.")


The 2-D matrix is not invertible.
The 3-D matrix is not invertible.

Inverse of 4-D Matrix:
[[[[-2.   1. ]
   [ 1.5 -0.5]]

  [[-4.   3. ]
   [ 3.5 -2.5]]]


 [[[-6.   5. ]
   [ 5.5 -4.5]]

  [[-8.   7. ]
   [ 7.5 -6.5]]]]

Inverse of 5-D Matrix:
[[[[[[ -2.    1. ]
     [  1.5  -0.5]]

    [[ -4.    3. ]
     [  3.5  -2.5]]]


   [[[ -6.    5. ]
     [  5.5  -4.5]]

    [[ -8.    7. ]
     [  7.5  -6.5]]]]



  [[[[-10.    9. ]
     [  9.5  -8.5]]

    [[-12.   11. ]
     [ 11.5 -10.5]]]


   [[[-14.   13. ]
     [ 13.5 -12.5]]

    [[-16.   15. ]
     [ 15.5 -14.5]]]]]]


In [9]:
A = np.array([[3, 1],
              [1, 2]])
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:")
print(eigenvalues)
print("\nEigenvectors:")
print(eigenvectors)

Eigenvalues:
[3.61803399 1.38196601]

Eigenvectors:
[[ 0.85065081 -0.52573111]
 [ 0.52573111  0.85065081]]


In [10]:
matrix_A = np.array([[3, 1],
                     [1, 2]])

matrix_B = np.array([[5, 2],
                     [2, 8]])

matrix_C = np.array([[4, -2],
                     [1, 3]])

matrix_D = np.array([[0, 1],
                     [1, 0]])

matrix_E = np.array([[6, 0],
                     [0, 3]])

def calculate_properties(matrix):
    rank = np.linalg.matrix_rank(matrix)
    diagonal_elements = np.diag(matrix)
    trace = np.trace(matrix)
    return rank, diagonal_elements, trace
matrices = [matrix_A, matrix_B, matrix_C, matrix_D, matrix_E]

for i, matrix in enumerate(matrices, start=1):
    rank, diagonal_elements, trace = calculate_properties(matrix)
    
    print(f"Matrix {i}:")
    print("Rank:", rank)
    print("Diagonal Elements:", diagonal_elements)
    print("Trace:", trace)
    print()


Matrix 1:
Rank: 2
Diagonal Elements: [3 2]
Trace: 5

Matrix 2:
Rank: 2
Diagonal Elements: [5 8]
Trace: 13

Matrix 3:
Rank: 2
Diagonal Elements: [4 3]
Trace: 7

Matrix 4:
Rank: 2
Diagonal Elements: [0 0]
Trace: 0

Matrix 5:
Rank: 2
Diagonal Elements: [6 3]
Trace: 9



In [11]:
from scipy import stats

def generate_random_dataset(size):
    return np.random.randint(1, 10, size)

datasets = [generate_random_dataset(10) for _ in range(5)]

for i, data in enumerate(datasets, start=1):
    print(f"Dataset {i}: {data}")
    print(f"Mean: {np.mean(data)}")
    print(f"Median: {np.median(data)}")
    
    try:
        mode_result = stats.mode(data)
        print(f"Mode: {mode_result.mode} (with a count of {mode_result.count[0]})")
    except stats.StatisticError:
        print("No unique mode")
    
    print()


Dataset 1: [5 9 9 9 7 6 5 6 2 5]
Mean: 6.3
Median: 6.0
Mode: [5] (with a count of 3)

Dataset 2: [9 2 5 6 9 9 8 7 9 5]
Mean: 6.9
Median: 7.5
Mode: [9] (with a count of 4)

Dataset 3: [7 9 4 5 6 3 5 1 4 3]
Mean: 4.7
Median: 4.5
Mode: [3] (with a count of 2)

Dataset 4: [6 1 3 9 7 8 6 5 2 5]
Mean: 5.2
Median: 5.5
Mode: [5] (with a count of 2)

Dataset 5: [8 2 6 7 1 9 6 6 4 7]
Mean: 5.6
Median: 6.0
Mode: [6] (with a count of 3)



In [12]:
import scipy.stats
def generate_random_datasets(size):
    data1 = np.random.randint(1, 100, size)
    data2 = np.random.randint(1, 100, size)
    return data1, data2
data1, data2 = generate_random_datasets(20)

covariance = np.cov(data1, data2)[0, 1]
pearson_corr = np.corrcoef(data1, data2)[0, 1]

spearman_corr, _ = scipy.stats.spearmanr(data1, data2)

print("Data 1:", data1)
print("Data 2:", data2)
print("Covariance:", covariance)
print("Pearson Correlation:", pearson_corr)
print("Spearman Correlation:", spearman_corr)


Data 1: [56 29 52 43 78 27 22 46 72 74 54 27 74 65  4 21 30 42 92 96]
Data 2: [ 7 94 83 68 46 42 93 70 10 18 66  3 94 25 53 31 39 17 24 32]
Covariance: -172.73684210526315
Pearson Correlation: -0.22392242346853447
Spearman Correlation: -0.17425669280843134


In [13]:
import pandas as pd
from scipy import stats

# Define the file path to your dataset in Google Drive
file_path = "C:\\Users\\Dell\\Downloads\\1_2015.xlsx"

# Load the dataset into a Pandas DataFrame
df = pd.read_excel(file_path)

# Calculate the mean
mean = df.mean()

# Calculate the median
median = df.median()

# Calculate the mode (returns a Series, as there can be multiple modes)
mode = stats.mode(df)

# Describe the dataset
description = df.describe()

# Display the results
print("Mean:")
print(mean)




Mean:
Happiness Rank\n1\n2\n3                         80.993548
Happiness Score\n7.587\n7.561\n7.527             5.333490
Standard Error\n0.03411\n0.04884\n0.03328        0.048062
Economy (GDP\n1.39651\n1.30232\n1.32548          0.836551
Family\n1.34951\n1.40223\n1.36058                0.983696
Health (Life Expe\n0.94143\n0.94784\n0.87464     0.624626
Freedom\n0.66557\n0.62877\n0.64938               0.424371
Trust (Governme\n0.41978\n0.14145\n0.48357       0.139457
Generosity\n0.29678\n0.4363\n0.34139             0.234956
dtype: float64


C:\Users\Dell\AppData\Local\Temp\ipykernel_8012\3517433423.py:11: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  mean = df.mean()
C:\Users\Dell\AppData\Local\Temp\ipykernel_8012\3517433423.py:14: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  median = df.median()


In [14]:
# Calculate the covariance matrix
covariance_matrix = df.cov()

# Calculate the Pearson correlation matrix
pearson_correlation_matrix = df.corr()

# Calculate the Spearman correlation matrix
spearman_correlation_matrix = df.corr(method='spearman')

# Display the results
print("Covariance Matrix:")
print(covariance_matrix)



Covariance Matrix:
                                              Happiness Rank\n1\n2\n3  \
Happiness Rank\n1\n2\n3                                   2014.980478   
Happiness Score\n7.587\n7.561\n7.527                       -49.629075   
Standard Error\n0.03411\n0.04884\n0.03328                    0.112719   
Economy (GDP\n1.39651\n1.30232\n1.32548                    -14.003391   
Family\n1.34951\n1.40223\n1.36058                           -8.736559   
Health (Life Expe\n0.94143\n0.94784\n0.87464                -8.029718   
Freedom\n0.66557\n0.62877\n0.64938                          -3.576887   
Trust (Governme\n0.41978\n0.14145\n0.48357                  -1.769811   
Generosity\n0.29678\n0.4363\n0.34139                        -0.760630   

                                              Happiness Score\n7.587\n7.561\n7.527  \
Happiness Rank\n1\n2\n3                                                 -49.629075   
Happiness Score\n7.587\n7.561\n7.527                                      1.24

In [15]:
print("\nMedian:")
print(median)



Median:
Happiness Rank\n1\n2\n3                         81.00000
Happiness Score\n7.587\n7.561\n7.527             5.19400
Standard Error\n0.03411\n0.04884\n0.03328        0.04394
Economy (GDP\n1.39651\n1.30232\n1.32548          0.90019
Family\n1.34951\n1.40223\n1.36058                1.02507
Health (Life Expe\n0.94143\n0.94784\n0.87464     0.69510
Freedom\n0.66557\n0.62877\n0.64938               0.43450
Trust (Governme\n0.41978\n0.14145\n0.48357       0.10583
Generosity\n0.29678\n0.4363\n0.34139             0.21488
dtype: float64


In [16]:

print("\nMode:")
print(mode)



Mode:
ModeResult(mode=array([['Israel', 'Sub-Saharan Afr', 82.0, 5.192, 0.04394, 0.0, 0.0,
        0.92356, 0.40672, 0.32524, 0.14574, 1.38079]], dtype=object), count=array([[ 1, 40,  2,  2,  2,  1,  1,  2,  1,  2,  1,  1]]))


In [17]:

print("\nDescription:")
print(description)


Description:
       Happiness Rank\n1\n2\n3  Happiness Score\n7.587\n7.561\n7.527  \
count               155.000000                            155.000000   
mean                 80.993548                              5.333490   
std                  44.888534                              1.114442   
min                   4.000000                              2.839000   
25%                  42.500000                              4.517500   
50%                  81.000000                              5.194000   
75%                 119.500000                              6.126500   
max                 158.000000                              7.522000   

       Standard Error\n0.03411\n0.04884\n0.03328  \
count                                 155.000000   
mean                                    0.048062   
std                                     0.017236   
min                                     0.018480   
25%                                     0.037400   
50%                      

In [18]:

print("\nSum")
print(df.sum())


print("\nCount:")
print(df.count())

print("\nMAX:\n")
print(df.max())

print("\n\nMin:")
print(df.min())


Sum
Happiness Rank\n1\n2\n3                         12554.00000
Happiness Score\n7.587\n7.561\n7.527              826.69100
Standard Error\n0.03411\n0.04884\n0.03328           7.44956
Economy (GDP\n1.39651\n1.30232\n1.32548           129.66537
Family\n1.34951\n1.40223\n1.36058                 152.47294
Health (Life Expe\n0.94143\n0.94784\n0.87464       96.81707
Freedom\n0.66557\n0.62877\n0.64938                 65.77744
Trust (Governme\n0.41978\n0.14145\n0.48357         21.61585
Generosity\n0.29678\n0.4363\n0.34139               36.41822
dtype: float64

Count:
Country Switzerland Iceland\nDenmark                    155
Region\nWestern Europe Western Europe Western Europe    155
Happiness Rank\n1\n2\n3                                 155
Happiness Score\n7.587\n7.561\n7.527                    155
Standard Error\n0.03411\n0.04884\n0.03328               155
Economy (GDP\n1.39651\n1.30232\n1.32548                 155
Family\n1.34951\n1.40223\n1.36058                       155
Health (Life

C:\Users\Dell\AppData\Local\Temp\ipykernel_8012\400085028.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  print(df.sum())
C:\Users\Dell\AppData\Local\Temp\ipykernel_8012\400085028.py:9: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  print(df.max())
C:\Users\Dell\AppData\Local\Temp\ipykernel_8012\400085028.py:12: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  print(df.min())


In [19]:
print("\nPearson Correlation Matrix:")
print(pearson_correlation_matrix)



Pearson Correlation Matrix:
                                              Happiness Rank\n1\n2\n3  \
Happiness Rank\n1\n2\n3                                      1.000000   
Happiness Score\n7.587\n7.561\n7.527                        -0.992073   
Standard Error\n0.03411\n0.04884\n0.03328                    0.145692   
Economy (GDP\n1.39651\n1.30232\n1.32548                     -0.778030   
Family\n1.34951\n1.40223\n1.36058                           -0.721553   
Health (Life Expe\n0.94143\n0.94784\n0.87464                -0.727056   
Freedom\n0.66557\n0.62877\n0.64938                          -0.534907   
Trust (Governme\n0.41978\n0.14145\n0.48357                  -0.340268   
Generosity\n0.29678\n0.4363\n0.34139                        -0.133937   

                                              Happiness Score\n7.587\n7.561\n7.527  \
Happiness Rank\n1\n2\n3                                                  -0.992073   
Happiness Score\n7.587\n7.561\n7.527                                

In [20]:

print("\nSpearman Correlation Matrix:")
print(spearman_correlation_matrix)



Spearman Correlation Matrix:
                                              Happiness Rank\n1\n2\n3  \
Happiness Rank\n1\n2\n3                                      1.000000   
Happiness Score\n7.587\n7.561\n7.527                        -1.000000   
Standard Error\n0.03411\n0.04884\n0.03328                    0.200500   
Economy (GDP\n1.39651\n1.30232\n1.32548                     -0.786290   
Family\n1.34951\n1.40223\n1.36058                           -0.756538   
Health (Life Expe\n0.94143\n0.94784\n0.87464                -0.746943   
Freedom\n0.66557\n0.62877\n0.64938                          -0.552849   
Trust (Governme\n0.41978\n0.14145\n0.48357                  -0.273649   
Generosity\n0.29678\n0.4363\n0.34139                        -0.140429   

                                              Happiness Score\n7.587\n7.561\n7.527  \
Happiness Rank\n1\n2\n3                                                  -1.000000   
Happiness Score\n7.587\n7.561\n7.527                               

In [21]:
import pandas as pd
from scipy import stats

# Define the file path to your dataset in Google Drive
file_path = "C:\\Users\\Dell\\Downloads\\3_Fitness.csv"

# Load the dataset into a Pandas DataFrame
df = pd.read_csv(file_path)

# Calculate the mean
mean = df.mean()

# Calculate the median
median = df.median()

# Calculate the mode (returns a Series, as there can be multiple modes)
mode = stats.mode(df)

# Describe the dataset
description = df.describe()

# Display the results
print("Mean:")
print(mean)




Mean:
JAN             101.090909
FEB              98.909091
MAR              94.909091
APR             103.818182
MAY              96.727273
JUN              85.090909
TOTAL SALES     579.818182
Unnamed: 8     3193.000000
Unnamed: 9             NaN
Unnamed: 10            NaN
dtype: float64


C:\Users\Dell\AppData\Local\Temp\ipykernel_8012\1518898070.py:11: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  mean = df.mean()
C:\Users\Dell\AppData\Local\Temp\ipykernel_8012\1518898070.py:14: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  median = df.median()


In [22]:

print("\nMedian:")
print(median)



Median:
JAN              65.0
FEB              54.0
MAR              50.0
APR              59.0
MAY              56.0
JUN              55.0
TOTAL SALES     322.0
Unnamed: 8     3193.0
Unnamed: 9        NaN
Unnamed: 10       NaN
dtype: float64


In [23]:

print("\nMode:")
print(mode)



Mode:
ModeResult(mode=array([['JOHN', 35.0, 35.0, 49.0, 45.0, 35.0, 25.0, 3189.0, 3193.0, 0, 0,
        '33']], dtype=object), count=array([[1, 2, 2, 2, 2, 2, 2, 1, 1, 0, 0, 1]]))


In [24]:

print("\nDescription:")
print(description)


Description:
              JAN         FEB         MAR         APR         MAY         JUN  \
count   11.000000   11.000000   11.000000   11.000000   11.000000   11.000000   
mean   101.090909   98.909091   94.909091  103.818182   96.727273   85.090909   
std    152.263886  148.884153  142.770763  155.277054  145.500578  128.347540   
min     29.000000   25.000000   15.000000   45.000000   25.000000   25.000000   
25%     35.000000   40.000000   47.000000   49.000000   40.000000   30.000000   
50%     65.000000   54.000000   50.000000   59.000000   56.000000   55.000000   
75%     76.000000   75.500000   71.500000   66.500000   69.500000   69.000000   
max    556.000000  544.000000  522.000000  571.000000  532.000000  468.000000   

       TOTAL SALES  Unnamed: 8  Unnamed: 9  Unnamed: 10  
count    11.000000         1.0         0.0          0.0  
mean    579.818182      3193.0         NaN          NaN  
std     869.142775         NaN         NaN          NaN  
min     210.000000      

In [25]:
print("\nSum")
print(df.sum())


print("\nCount:")
print(df.count())

print("\nMAX:\n")
print(df.max())

print("\n\nMin:")
print(df.min())


Sum
JAN            1112.0
FEB            1088.0
MAR            1044.0
APR            1142.0
MAY            1064.0
JUN             936.0
TOTAL SALES    6378.0
Unnamed: 8     3193.0
Unnamed: 9        0.0
Unnamed: 10       0.0
dtype: float64

Count:
SALESMAN       11
JAN            11
FEB            11
MAR            11
APR            11
MAY            11
JUN            11
TOTAL SALES    11
Unnamed: 8      1
Unnamed: 9      0
Unnamed: 10     0
Unnamed: 11     6
dtype: int64

MAX:

JAN             556.0
FEB             544.0
MAR             522.0
APR             571.0
MAY             532.0
JUN             468.0
TOTAL SALES    3189.0
Unnamed: 8     3193.0
Unnamed: 9        NaN
Unnamed: 10       NaN
dtype: float64


Min:
JAN              29.0
FEB              25.0
MAR              15.0
APR              45.0
MAY              25.0
JUN              25.0
TOTAL SALES     210.0
Unnamed: 8     3193.0
Unnamed: 9        NaN
Unnamed: 10       NaN
dtype: float64


C:\Users\Dell\AppData\Local\Temp\ipykernel_8012\2817304812.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  print(df.sum())
C:\Users\Dell\AppData\Local\Temp\ipykernel_8012\2817304812.py:9: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  print(df.max())
C:\Users\Dell\AppData\Local\Temp\ipykernel_8012\2817304812.py:12: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  print(df.min())


In [26]:
# Calculate the covariance matrix
covariance_matrix = df.cov()

# Calculate the Pearson correlation matrix
pearson_correlation_matrix = df.corr()

# Calculate the Spearman correlation matrix
spearman_correlation_matrix = df.corr(method='spearman')

# Display the results
print("Covariance Matrix:")
print(covariance_matrix)



Covariance Matrix:
                      JAN           FEB           MAR           APR  \
JAN          23184.290909  22574.709091  21648.309091  23552.818182   
FEB          22574.709091  22166.490909  21156.490909  23010.281818   
MAR          21648.309091  21156.490909  20383.490909  22093.081818   
APR          23552.818182  23010.281818  22093.081818  24110.963636   
MAY          22013.827273  21464.272727  20643.572727  22517.645455   
JUN          19182.690909  18734.209091  18079.509091  19737.218182   
TOTAL SALES   1600.066667   1342.711111   1414.022222    857.344444   
Unnamed: 8            NaN           NaN           NaN           NaN   
Unnamed: 9            NaN           NaN           NaN           NaN   
Unnamed: 10           NaN           NaN           NaN           NaN   

                      MAY           JUN    TOTAL SALES  Unnamed: 8  \
JAN          22013.827273  19182.690909    1600.066667         NaN   
FEB          21464.272727  18734.209091    1342.711111     

In [27]:
print("\nPearson Correlation Matrix:")
print(pearson_correlation_matrix)




Pearson Correlation Matrix:
                  JAN       FEB       MAR       APR       MAY       JUN  \
JAN          1.000000  0.995811  0.995836  0.996182  0.993651  0.981579   
FEB          0.995811  1.000000  0.995304  0.995328  0.990839  0.980391   
MAR          0.995836  0.995304  1.000000  0.996574  0.993759  0.986642   
APR          0.996182  0.995328  0.996574  1.000000  0.996669  0.990355   
MAY          0.993651  0.990839  0.993759  0.996669  1.000000  0.988690   
JUN          0.981579  0.980391  0.986642  0.990355  0.988690  1.000000   
TOTAL SALES  0.867710  0.771350  0.880879  0.941904  0.814248  0.419371   
Unnamed: 8        NaN       NaN       NaN       NaN       NaN       NaN   
Unnamed: 9        NaN       NaN       NaN       NaN       NaN       NaN   
Unnamed: 10       NaN       NaN       NaN       NaN       NaN       NaN   

             TOTAL SALES  Unnamed: 8  Unnamed: 9  Unnamed: 10  
JAN             0.867710         NaN         NaN          NaN  
FEB             0

In [28]:
print("\nSpearman Correlation Matrix:")
print(spearman_correlation_matrix)



Spearman Correlation Matrix:
                  JAN       FEB       MAR       APR       MAY       JUN  \
JAN          1.000000  0.824201  0.812785  0.924658  0.778034  0.252880   
FEB          0.824201  1.000000  0.815068  0.767123  0.583526  0.197706   
MAR          0.812785  0.815068  1.000000  0.936073  0.805494  0.397711   
APR          0.924658  0.767123  0.936073  1.000000  0.860414  0.434493   
MAY          0.778034  0.583526  0.805494  0.860414  1.000000  0.476964   
JUN          0.252880  0.197706  0.397711  0.434493  0.476964  1.000000   
TOTAL SALES  0.881463  0.747724  0.911858  0.948333  0.786600  0.343584   
Unnamed: 8        NaN       NaN       NaN       NaN       NaN       NaN   
Unnamed: 9        NaN       NaN       NaN       NaN       NaN       NaN   
Unnamed: 10       NaN       NaN       NaN       NaN       NaN       NaN   

             TOTAL SALES  Unnamed: 8  Unnamed: 9  Unnamed: 10  
JAN             0.881463         NaN         NaN          NaN  
FEB             

In [29]:
import pandas as pd
from scipy import stats

# Define the file path to your dataset in Google Drive
file_path = "C:\\Users\\Dell\\Downloads\\4_Drug200.csv"

# Load the dataset into a Pandas DataFrame
df = pd.read_csv(file_path)

# Calculate the mean
mean = df.mean()

# Calculate the median
median = df.median()

# Calculate the mode (returns a Series, as there can be multiple modes)
mode = stats.mode(df)

# Describe the dataset
description = df.describe()

# Display the results
print("Mean:")
print(mean)



Mean:
Age        44.315000
Na_to_K    16.084485
dtype: float64


C:\Users\Dell\AppData\Local\Temp\ipykernel_8012\3804751763.py:11: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  mean = df.mean()
C:\Users\Dell\AppData\Local\Temp\ipykernel_8012\3804751763.py:14: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  median = df.median()


In [30]:
print("\nMedian:")
print(median)




Median:
Age        45.0000
Na_to_K    13.9365
dtype: float64


In [31]:
print("\nMode:")
print(mode)




Mode:
ModeResult(mode=array([[47, 'M', 'HIGH', 'HIGH', 12.006, 'drugY']], dtype=object), count=array([[  8, 104,  77, 103,   2,  91]]))


In [32]:
print("\nDescription:")
print(description)



Description:
              Age     Na_to_K
count  200.000000  200.000000
mean    44.315000   16.084485
std     16.544315    7.223956
min     15.000000    6.269000
25%     31.000000   10.445500
50%     45.000000   13.936500
75%     58.000000   19.380000
max     74.000000   38.247000


In [33]:
print("\nSum")
print(df.sum())


print("\nCount:")
print(df.count())

print("\nMAX:\n")
print(df.max())

print("\n\nMin:")
print(df.min())


Sum
Age                                                         8863
Sex            FMMFFFFMMMFFMFFFMMMFMMMFFFMFFMFMMFMMMMFMFFMMFF...
BP             HIGHLOWLOWNORMALLOWNORMALNORMALLOWNORMALLOWLOW...
Cholesterol    HIGHHIGHHIGHHIGHHIGHHIGHHIGHHIGHHIGHNORMALHIGH...
Na_to_K                                                 3216.897
Drug           drugYdrugCdrugCdrugXdrugYdrugXdrugYdrugCdrugYd...
dtype: object

Count:
Age            200
Sex            200
BP             200
Cholesterol    200
Na_to_K        200
Drug           200
dtype: int64

MAX:

Age                74
Sex                 M
BP             NORMAL
Cholesterol    NORMAL
Na_to_K        38.247
Drug            drugY
dtype: object


Min:
Age               15
Sex                F
BP              HIGH
Cholesterol     HIGH
Na_to_K        6.269
Drug           drugA
dtype: object


In [34]:
# Calculate the covariance matrix
covariance_matrix = df.cov()

# Calculate the Pearson correlation matrix
pearson_correlation_matrix = df.corr()

# Calculate the Spearman correlation matrix
spearman_correlation_matrix = df.corr(method='spearman')

# Display the results
print("Covariance Matrix:")
print(covariance_matrix)



Covariance Matrix:
                Age    Na_to_K
Age      273.714347  -7.543752
Na_to_K   -7.543752  52.185533


In [35]:
print("\nPearson Correlation Matrix:")
print(pearson_correlation_matrix)




Pearson Correlation Matrix:
              Age   Na_to_K
Age      1.000000 -0.063119
Na_to_K -0.063119  1.000000


In [36]:
print("\nSpearman Correlation Matrix:")
print(spearman_correlation_matrix)



Spearman Correlation Matrix:
              Age   Na_to_K
Age      1.000000 -0.047274
Na_to_K -0.047274  1.000000


In [37]:
import pandas as pd
from scipy import stats

# Define the file path to your dataset in Google Drive
file_path = "C:\\Users\\Dell\\Downloads\\6_salesworkload.xlsx"

# Load the dataset into a Pandas DataFrame
df = pd.read_excel(file_path)


# Calculate the mode (returns a Series, as there can be multiple modes)
mode = stats.mode(df)

# Describe the dataset
description = df.describe()

# Display the results
print("mode:")
print(mode)



mode:
ModeResult(mode=array([['10.2016', 1, 'Germany', 98422, 'Bologna', 1, 'Frozen', 47.205,
        0, 0, 0, 'Customer', 0, 'Type A']], dtype=object), count=array([[ 850,  850,  918,  153,  153,  450,  450,  450, 7172,  157, 1480,
           1, 1600, 5661]]))


In [38]:
print("\nDescription:")
print(description)


Description:
       Unnamed: 0  Unnamed: 1      Unnamed: 2  Unnamed: 3     Unnamed: 4  \
count        7659        7651            7651        7651           7651   
unique         11          10              12          51             51   
top       10.2016           1  United Kingdom       16927  Barcelona (I)   
freq          850         850             918         153            153   

        Unnamed: 5 Unnamed: 6  Unnamed: 7  Unnamed: 8  Unnamed: 9  \
count         7651       7651    7651.000        7651        7651   
unique          18         18    3506.000         224        5659   
top              8  Household      47.205           0           0   
freq           450        450     450.000        7172         157   

        Unnamed: 10 Unnamed: 11  Unnamed: 12 Unnamed: 13  
count          7651           1         7651        7651  
unique         5905           1         2827           4  
top               0    Customer            0      Type A  
freq           1480    

In [39]:
print("\nSum")
print(df.sum())


print("\nCount:")
print(df.count())

print("\nMAX:\n")
print(df.max())

print("\n\nMin:")
print(df.min())


Sum
Unnamed: 0    MonthYear10.201610.201610.201610.201610.201610...
dtype: object

Count:
Unnamed: 0     7659
Unnamed: 1     7651
Unnamed: 2     7651
Unnamed: 3     7651
Unnamed: 4     7651
Unnamed: 5     7651
Unnamed: 6     7651
Unnamed: 7     7651
Unnamed: 8     7651
Unnamed: 9     7651
Unnamed: 10    7651
Unnamed: 11       1
Unnamed: 12    7651
Unnamed: 13    7651
dtype: int64

MAX:

Unnamed: 0    MonthYear
dtype: object


Min:
Unnamed: 0     - - - - 
dtype: object


C:\Users\Dell\AppData\Local\Temp\ipykernel_8012\2817304812.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  print(df.sum())
C:\Users\Dell\AppData\Local\Temp\ipykernel_8012\2817304812.py:9: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  print(df.max())
C:\Users\Dell\AppData\Local\Temp\ipykernel_8012\2817304812.py:12: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  print(df.min())


In [40]:
# Calculate the covariance matrix
covariance_matrix = df.cov()

# Calculate the Pearson correlation matrix
pearson_correlation_matrix = df.corr()

# Calculate the Spearman correlation matrix
spearman_correlation_matrix = df.corr(method='spearman')

# Display the results
print("Covariance Matrix:")
print(covariance_matrix)



Covariance Matrix:
Empty DataFrame
Columns: []
Index: []


In [41]:
print("\nPearson Correlation Matrix:")
print(pearson_correlation_matrix)




Pearson Correlation Matrix:
Empty DataFrame
Columns: []
Index: []


In [42]:
print("\nSpearman Correlation Matrix:")
print(spearman_correlation_matrix)



Spearman Correlation Matrix:
Empty DataFrame
Columns: []
Index: []


In [43]:
import pandas as pd
from scipy import stats

# Define the file path to your dataset in Google Drive
file_path = "C:\\Users\\Dell\\Downloads\\7_Uber.csv"

# Load the dataset into a Pandas DataFrame
df = pd.read_csv(file_path)

# Calculate the mean
mean = df.mean()

# Calculate the median
median = df.median()

# Calculate the mode (returns a Series, as there can be multiple modes)
mode = stats.mode(df)

# Describe the dataset
description = df.describe()

# Display the results
print("Mean:")
print(mean)




C:\Users\Dell\AppData\Local\Temp\ipykernel_8012\4275267299.py:11: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  mean = df.mean()
C:\Users\Dell\AppData\Local\Temp\ipykernel_8012\4275267299.py:14: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  median = df.median()


Mean:
Unnamed: 0           2.771250e+07
fare_amount          1.135996e+01
pickup_longitude    -7.252764e+01
pickup_latitude      3.993589e+01
dropoff_longitude   -7.252529e+01
dropoff_latitude     3.992389e+01
passenger_count      1.684535e+00
dtype: float64


In [44]:
print("\nMedian:")
print(median)




Median:
Unnamed: 0           2.774550e+07
fare_amount          8.500000e+00
pickup_longitude    -7.398182e+01
pickup_latitude      4.075259e+01
dropoff_longitude   -7.398009e+01
dropoff_latitude     4.075304e+01
passenger_count      1.000000e+00
dtype: float64


In [45]:
print("\nMode:")
print(mode)




Mode:
ModeResult(mode=array([[1, '2009-01-01 01:15:22.0000006', 6.5, '2009-02-12 12:46:00 UTC',
        0.0, 0.0, 0.0, 0.0, 1]], dtype=object), count=array([[     1,      1,   9684,      4,   3786,   3782,   3764,   3758,
        138425]]))


In [46]:
print("\nDescription:")
print(description)


Description:
         Unnamed: 0    fare_amount  pickup_longitude  pickup_latitude  \
count  2.000000e+05  200000.000000     200000.000000    200000.000000   
mean   2.771250e+07      11.359955        -72.527638        39.935885   
std    1.601382e+07       9.901776         11.437787         7.720539   
min    1.000000e+00     -52.000000      -1340.648410       -74.015515   
25%    1.382535e+07       6.000000        -73.992065        40.734796   
50%    2.774550e+07       8.500000        -73.981823        40.752592   
75%    4.155530e+07      12.500000        -73.967154        40.767158   
max    5.542357e+07     499.000000         57.418457      1644.421482   

       dropoff_longitude  dropoff_latitude  passenger_count  
count      199999.000000     199999.000000    200000.000000  
mean          -72.525292         39.923890         1.684535  
std            13.117408          6.794829         1.385997  
min         -3356.666300       -881.985513         0.000000  
25%           -73.

In [47]:
print("\nSum")
print(df.sum())


print("\nCount:")
print(df.count())

print("\nMAX:\n")
print(df.max())

print("\n\nMin:")
print(df.min())


Sum
Unnamed: 0                                               5542500736470
key                  2015-05-07 19:52:06.00000032009-07-17 20:04:56...
fare_amount                                                 2271991.05
pickup_datetime      2015-05-07 19:52:06 UTC2009-07-17 20:04:56 UTC...
pickup_longitude                                      -14505527.583247
pickup_latitude                                         7987177.075602
dropoff_longitude                                     -14504985.800203
dropoff_latitude                                        7984738.156476
passenger_count                                                 336907
dtype: object

Count:
Unnamed: 0           200000
key                  200000
fare_amount          200000
pickup_datetime      200000
pickup_longitude     200000
pickup_latitude      200000
dropoff_longitude    199999
dropoff_latitude     199999
passenger_count      200000
dtype: int64

MAX:

Unnamed: 0                              55423567
key          

In [48]:
# Calculate the covariance matrix
covariance_matrix = df.cov()

# Calculate the Pearson correlation matrix
pearson_correlation_matrix = df.corr()

# Calculate the Spearman correlation matrix
spearman_correlation_matrix = df.corr(method='spearman')

# Display the results
print("Covariance Matrix:")
print(covariance_matrix)




Covariance Matrix:
                     Unnamed: 0   fare_amount  pickup_longitude  \
Unnamed: 0         2.564425e+14  93377.989460      42073.899752   
fare_amount        9.337799e+04     98.045172          1.184331   
pickup_longitude   4.207390e+04      1.184331        130.822979   
pickup_latitude   -4.211348e+04     -0.648348        -72.098340   
dropoff_longitude  5.668481e+04      1.167142        124.982650   
dropoff_latitude   2.953191e+04     -0.741010        -65.774618   
passenger_count    5.009811e+04      0.139296         -0.006569   

                   pickup_latitude  dropoff_longitude  dropoff_latitude  \
Unnamed: 0           -42113.484736       56684.809962      29531.911296   
fare_amount              -0.648348           1.167142         -0.741010   
pickup_longitude        -72.098340         124.982650        -65.774618   
pickup_latitude          59.606729         -78.465589         36.846061   
dropoff_longitude       -78.465589         172.066387        -81.7336

In [49]:
print("\nPearson Correlation Matrix:")
print(pearson_correlation_matrix)




Pearson Correlation Matrix:
                   Unnamed: 0  fare_amount  pickup_longitude  pickup_latitude  \
Unnamed: 0           1.000000     0.000589          0.000230        -0.000341   
fare_amount          0.000589     1.000000          0.010457        -0.008481   
pickup_longitude     0.000230     0.010457          1.000000        -0.816461   
pickup_latitude     -0.000341    -0.008481         -0.816461         1.000000   
dropoff_longitude    0.000270     0.008986          0.833026        -0.774787   
dropoff_latitude     0.000271    -0.011014         -0.846324         0.702367   
passenger_count      0.002257     0.010150         -0.000414        -0.001560   

                   dropoff_longitude  dropoff_latitude  passenger_count  
Unnamed: 0                  0.000270          0.000271         0.002257  
fare_amount                 0.008986         -0.011014         0.010150  
pickup_longitude            0.833026         -0.846324        -0.000414  
pickup_latitude           

In [50]:
print("\nSpearman Correlation Matrix:")
print(spearman_correlation_matrix)


Spearman Correlation Matrix:
                   Unnamed: 0  fare_amount  pickup_longitude  pickup_latitude  \
Unnamed: 0           1.000000     0.000669          0.003189         0.002928   
fare_amount          0.000669     1.000000          0.042732        -0.073551   
pickup_longitude     0.003189     0.042732          1.000000         0.513365   
pickup_latitude      0.002928    -0.073551          0.513365         1.000000   
dropoff_longitude    0.006621     0.102393          0.403647         0.196940   
dropoff_latitude     0.002639    -0.086520          0.215534         0.497906   
passenger_count      0.003308     0.023296         -0.016158        -0.015759   

                   dropoff_longitude  dropoff_latitude  passenger_count  
Unnamed: 0                  0.006621          0.002639         0.003308  
fare_amount                 0.102393         -0.086520         0.023296  
pickup_longitude            0.403647          0.215534        -0.016158  
pickup_latitude          